install_packages: modify script and update list

diff --git a/make_scripts/make_install_packages b/make_scripts/make_install_packages
--- a/make_scripts/make_install_packages
+++ b/make_scripts/make_install_packages
@@ -1,160 +1,57 @@
 #!/usr/bin/env sh
 # vim: ft=sh
 
-GIT=/usr/bin/git
-MAKEPKG=/usr/bin/makepkg
-PACAUR=/usr/bin/yay
-PACMAN=/usr/bin/pacman
-SUDO=/usr/bin/sudo
+git=$(command -v git)
+makepkg=$(command -v makepkg)
+sudo=$(command -v sudo)
+package_list=${PACKAGE_LIST:-"package_list.txt"}
+
+echo "=== Package Installer ==="
+if [ ! -f "$package_list" ]; then
+    echo "Please use a correct package_list.txt"
+    exit 1
+fi
+echo "Package List: $(realpath "$package_list")"
+echo
 
 # Get the passwd for sudo
-$SUDO -v
+$sudo -v
 
 # Keep sudo alive through the hole script
-while true; do $SUDO -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
+while true; do $sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
 
-PACK_GROUPS=(
-    "base-devel"
-    "texlive-most"
-)
-
-PACKAGES=(
-    "acpi"
-    "alsa-tools"
-    "alsa-utils"
-    "arandr"
-    "bleachbit"
-    "bind-tools"
-    "chromium"
-    "cmake"
-    "compton"
-    "diff-so-fancy"
-    "dunst"
-    "exfat-utils"
-    "f2fs-tools"
-    "fd"
-    "feh"
-    "firefox"
-    "fontconfig"
-    "freetype2"
-    "fzf"
-    "ghostscript"
-    "gdisk"
-    "gimp"
-    "gnome-keyring"
-    "gsimplecal"
-    "gtk2"
-    "gtk3"
-    "htop"
-    "hugo"
-    "imagemagick"
-    "keybase"
-    "keybase-gui"
-    "linux-headers"
-    "linux-lts"
-    "make"
-    "mpv"
-    "mtpfs"
-    "neomutt"
-    "neovim"
-    "ntfs-3g"
-    "openssh"
-    "openssl"
-    "p7zip"
-    "pacman-contrib"
-    "pass"
-    "pass-otp"
-    "pavucontrol"
-    "perl-file-mimeinfo"
-    "pkg-config"
-    "playerctl"
-    "ponymix"
-    "pulseaudio"
-    "pulseaudio-alsa"
-    "python"
-    "python-neovim"
-    "python-unidecode"
-    "python2"
-    "python2-neovim"
-    "qt4"
-    "r"
-    "ranger"
-    "redshift"
-    "reflector"
-    "ripgrep"
-    "rsync"
-    "rustup"
-    "scrot"
-    "stow"
-    "thunderbird"
-    "tlp"
-    "tmux"
-    "vlc"
-    "w3m"
-    "xclip"
-    "zathura"
-    "zathura-pdf-mupdf"
-    "zlib"
-)
-
-AURPACKAGES=(
-    "checkupdates+aur"
-    "gitflow-avh"
-    "gitflow-zshcompletion-avh"
-    "gtk-theme-united-gnome"
-    "jabref"
-    "jdk"
-    "nerd-fonts-complete"
-    "nextcloud-client"
-    "polybar"
-    "rofi-pass"
-    "spotify"
-    "standardnotes-desktop"
-    "teamviewer"
-    "wpa-cute"
-)
-
-echo -e "\nInstalling packages from groups..."
-for GROUP in ${PACK_GROUPS[@]} ; do
-    PACKS=$($PACMAN -Sg $GROUP | awk -F ' ' '{print $2}')
-    for PACK in ${PACKS[@]} ; do
-        if ! $PACMAN -Q $PACK > /dev/null ; then
-            echo -e "\nInstalling package: '$PACK'..."
-            $SUDO $PACMAN -S $PACK --needed --noconfirm
-            echo -e "Package successfully installed: '$PACK'\n"
-        fi
-    done
-done
-
-echo -e "\nInstalling packages from official repo..."
-for PACK in ${PACKAGES[@]} ; do
-    if ! $PACMAN -Q $PACK > /dev/null ; then
-        echo -e "\nInstalling package: '$PACK'..."
-        $SUDO $PACMAN -S $PACK --needed --noconfirm
-        echo -e "Package successfully installed: '$PACK'\n"
-    fi
-done
-
-echo -e "\nInstalling packages from AUR"
-if ! $PACMAN -Q yay-bin > /dev/null ; then
-    echo -e "\nInstalling AUR helper 'yay'..."
+# Check if yay is installed and if not, install it
+if ! [ -x "$(command -v yay)" ]; then
+    echo "Installing yay..."
     dir=$(pwd)
-    cd $(mktemp -d)
-    $GIT clone https://aur.archlinux.org/yay-bin.git
-    cd yay-bin
-    $MAKEPKG -si
-    cd ..
-    rm -rf yay-bin
-    cd $dir
-    echo -e "AUR Helper 'yay' successfully installed\n"
+    cd "$(mktemp -d)" || exit
+    $git clone https://aur.archlinux.org/yay-bin.git
+    cd yay-bin || exit
+    if ! $makepkg -si --noconfirm; then
+        echo "Error installing yay" >&2
+        exit 1
+    fi
+    cd "$dir" || exit
+    echo "yay successfully installed"
 fi
 
-for PACK in ${AURPACKAGES[@]}; do
-    if ! $PACMAN -Qs $PACK > /dev/null ; then
-        echo -e "\nInstalling package: '$PACK'..."
-        $PACAUR -S $PACK --needed --noconfirm
-        echo -e "Package successfully installed: '$PACK'\n"
+pacaur=$(command -v yay)
+error_pkgs=""
+echo "Installing packages..."
+while IFS= read -r package; do
+    if ! $pacaur -S --needed --noconfirm --quiet "$package"; then
+        echo "Error installing package $package" >&2
+        error_pkgs="${error_pkgs} $package"
     fi
-done
+done < "$package_list"
 
-echo -e "\nAll packages were installed\n"
+if [ -n "$error_pkgs" ]; then
+    echo
+    echo "The following packages could not be installed in the system:"
+    echo "${error_pkgs}"
+    echo
+fi
+
+echo
+echo "All packages were installed"
+exit 0
